replicatedhq/replicated-field-labs

lab1-kots/lab1-e6-proxy/README.md

Change original two line command: 
```bash
ssh -vNL 8800:${REPLICATED_APP}-lab1-e6-proxy:8800 ${JUMP_BOX_IP}
```
```bash
ssh -vNL 8888:${REPLICATED_APP}-lab1-e6-proxy:8888 ${JUMP_BOX_IP}
```
to one line command:
```bash
ssh -vNL 8800:${REPLICATED_APP}-lab1-e6-proxy:8800 -L 8888:${REPLICATED_APP}-lab1-e6-proxy:8888 ${JUMP_BOX_IP}
```

- Update lab1-e6 configuring instance to one line command

---

labs/lab10-demo/README.md

1. don't use shell interpolation syntax (e.g. `$IP_ADDRESS`) outside of shell commands.
1. Use `http://` instead of `https://` so user does not bypass TLS setup screens
1. Add `Advanced` tag to etc hosts section so folks know to skip it.

Lab 10 tweaks for usability

---

labs/lab05-airgap/README.md

A couple small suggestions for clarification:
- Removed "you can" from the sentence, "If you haven't already, you can log out of the Air Gap instance...". "You can" makes this step sound optional, whereas you do need to log out of the airgap instance and instead connect to the jumpbox for these steps. I missed this on my first step, and it took me a minute to realize I was still connected to the airgap instance.
- Added a bit of clarification around which URL you are copying into the curl command.

Minor edits for clarification

---

labs/lab00-hello-world/README.md

The Docker references aren't true anymore I've just removed references to using them with kURL

Remove references to Docker

---

labs/lab01-ui-analyzers/README.md

Just a small one, noticed the link for lab01 kots ui was for lab00.
Signed-off-by: Dan Jones <danj@replicated.com>

Correct link for lab01 kots ui

---

instruqt/shell-and-cluster-template/01-validate-connectivity/assignment.md
instruqt/shell-and-cluster-template/01-validate-connectivity/check-shell
instruqt/shell-and-cluster-template/config.yml
instruqt/shell-and-cluster-template/track.yml
instruqt/shell-and-cluster-template/track_scripts/setup-cluster
instruqt/shell-and-cluster-template/track_scripts/setup-shell

TL;DR
-----
Providse a templates track for a shell running independently of the K8s cluster
Details
-------
My first attempts at setting up a lab where the shell for running CLI commands is
independent of the Kubernetes cluster they are run against ran into issues with
the way that the Instruqt bootstrap injects SSH keys and the Dropbear server. This
change captures the pattern I used to workaround the limitations that caused my
earlier lifecycle scripts to fail.
When configurating a track with this setup, the best way to assure access to the
K8s cluster is to take the default config from `/etc/rancher/k3s/k3s.yaml` and
use it from shell host in the sandbox. My first attempts at this ran into two
issues:
1. The timing of `/etc/rancher/k3s/k3s.yaml` being available.  The best way
around …

Adds a template for a shell + cluster lab

---

instruqt/shell-and-cluster-template/config.yml

TL;DR
-----
Corrects copy/paste error in the Shell/Cluster template
Details
-------
Uses the `gcr.io/kots-field-labs/shell` image in the Shell and
Cluster template rather than the lab specific image for the CLI
lab.

Refers to correct image in Shell/Cluster template

---

instruqt/redactors/02-redactors-overview/assignment.md

Vendor Portal was not opening on challenge 2 as I did not have 'new_window:true' set.
This PR adds that line to the **Vendor** section

Redactor Lab fix for Challenge #2

---

instruqt/custom-fields/04-setting-the-custom-field/assignment.md

Corrects the instructions to have the user select the Stable channel

Update Instructions to have License use the Stable channel

---

.github/workflows/build-jumpbox-image.yaml

TL;DR
-----
Makes the jumpbox build integration github action work
Details
-------
Updates the jumpbox build integration github action to call Packer
correctly and to only build/replace the image on merge.

Fixes Jumpbox packer build automation

---

instruqt/airgap-embedded/01-airgap-overview/solve-jumpbox
instruqt/airgap-embedded/02-prepare-your-jumpbox/solve-jumpbox
instruqt/airgap-embedded/03-airgap-deployment-assets/check-jumpbox
instruqt/airgap-embedded/03-airgap-deployment-assets/solve-jumpbox
instruqt/airgap-embedded/04-building-an-air-gap-release/assignment.md
instruqt/airgap-embedded/04-building-an-air-gap-release/solve-jumpbox
instruqt/airgap-embedded/05-moving-assets-into-place/check-jumpbox
instruqt/airgap-embedded/05-moving-assets-into-place/cleanup-jumpbox
instruqt/airgap-embedded/05-moving-assets-into-place/solve-jumpbox
instruqt/airgap-embedded/track.yml

TL;DR
-----
Makes the tests pass
Details
-------
Addresses issues with missing `tmux` session cauasing solve scripts
to fail. Getting the session in place made the tests progress, but 
only to another script that failed. Made some additional changes to
make sure they other failures were resolved as well.
Along the way I realized an opporunity to improve the checks for the
"Building an Airgap Bundle" challenge. This meant a bit of messing 
around with the Vendor Portal API to get both check and solve for the
setting the channel and customer up for airgap. Those changes are 
also part of this PR.
To Do
-----
Some challenges still put a test marker in place in their solve 
script, then bypass their checks if the marker is in place. I have
plans for real solve scripts for them.

Repairs solve scripts so tests complete

---

CODEOWNERS

TL;DR
-----
Brings `CODEOWNERS` up to date
Details
-------
Records the current members of the Replicated SE team as the code owners for the entire repository.

Updates the list of owners to the full SE team

---

instruqt/helm-hello-world/02-getting/assignment.md

The text used to say 'existing install' However, the vendor portal UI actually says 'Existing Cluster'

Change text to match vendor portal UI

---

instruqt/support-cli/track.yml

This is the only one that isn't capitalized.

Capitalize first word of teaser

---

CODEOWNERS

TL;DR
-----
Makes sure the right folks are listed as code owners
Details
-------
Removes former team members an adds current team members to that
the right folks are listed as owners on this repo.

Updates `CODEOWNERS`

---

instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/setup-shell
instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/solve-shell
instruqt/avoiding-installation-pitfalls/track.yml
instruqt/closing-information-gap/01-viewing-instance-info/assignment.md
instruqt/closing-information-gap/06-support-bundle-diagnosis/setup-shell
instruqt/closing-information-gap/track.yml
instruqt/closing-information-gap/track_scripts/setup-shell
instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/assignment.md
instruqt/distributing-with-replicated/04-installing-the-application/setup-shell
instruqt/distributing-with-replicated/track.yml

TL;DR
-----
Updates lab to enable a Builders Plan only team
Details
-------
Converts code that looked at the license to find the regitry password to use
the installation ID from the customer record. This enables us to switch from
using the same team for all labs to using two different teams: one for the
Builders experience and one for the Premium experience. 
The changes to use two different teams is entirely at the Zepier level, so you
won't find it in this codebase.

Enables labs to run with a Builders Plan only team

---

instruqt/avoiding-installation-pitfalls/track_scripts/setup-shell
instruqt/closing-information-gap/track_scripts/setup-shell
instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/assignment.md
instruqt/distributing-with-replicated/02-enabling-the-sdk/assignment.md
instruqt/distributing-with-replicated/02-enabling-the-sdk/solve-shell
instruqt/distributing-with-replicated/track.yml

TL;DR
-----
Pins Harbor version, updates Replicated SDK
Details
-------
Makes two changes related to versioning:
* Updates the version of the Replicated SDK in the to alpha 17
* "Pins" the Harbor version by downloading a specific version of the chart, so
that all of the version bumps in the labs make sense

Updates for Harbor and SDK version bumps

---

instruqt/avoiding-installation-pitfalls/04-releasing-the-application/assignment.md
instruqt/avoiding-installation-pitfalls/track.yml
instruqt/closing-information-gap/05-releasing-an-update/assignment.md
instruqt/closing-information-gap/track.yml
instruqt/distributing-with-replicated/03-creating-a-release/assignment.md
instruqt/distributing-with-replicated/track.yml

TL;DR
-----
Update release promotion instructions to use match existing sequence
numbers
Details
-------
Up until recently every Builders experience lab started with an empty
release of the application. This was kind of accidental: the lab
automation creates a release for the application, and those labs didn't
really need one. It worked out OK since the Vendor Portal allowed the
empty release and the lab instructions took the release into account.
This all changed when the Vendor portal team tighten the constraints on
releases, at least for Builders experience applications. The empty
release doesn't have a Helm chart in it. So no release is created and
the automation silently failed. The labs continued to work since the
release is created near the end and everything the labs need was in …

Fixes release promotion instructions

---

instruqt/closing-information-gap/04-adding-to-the-chart/check-shell

```  
let "reasult = result + 1"
```
assuming this should be `result =` from context

Update check-shell - fix another typo

---

instruqt/shared-env-template/01-getting-to-know-the-template/assignment.md
instruqt/shared-env-template/01-getting-to-know-the-template/check-shell
instruqt/shared-env-template/01-getting-to-know-the-template/cleanup-shell
instruqt/shared-env-template/01-getting-to-know-the-template/setup-shell
instruqt/shared-env-template/01-getting-to-know-the-template/solve-shell
instruqt/shared-env-template/02-using-the-template/assignment.md
instruqt/shared-env-template/02-using-the-template/check-shell
instruqt/shared-env-template/02-using-the-template/cleanup-shell
instruqt/shared-env-template/02-using-the-template/solve-shell
instruqt/shared-env-template/03-tips-and-tricks/assignment.md
instruqt/shared-env-template/config.yml
instruqt/shared-env-template/track.yml
instruqt/shared-env-template/track_scripts/setup-cluster
instruqt/shared-env-template/track_scripts/setup-shell

TL;DR
-----
Generatlizes `tmux` model from `airgap-embedded` as a template
Details
-------
Offers a template for new labs that want to share the same shell
between challenges based on the work I did on `airgap-embedded`
with `tmux`.
This template is a useful for labs need to set some environment 
variables in on challenge and use them in anither, or where a 
challenge starts  a long-running process, among other things. It
also feels a bit more like how a tutorial might feel in a non-lab
environment where you do everything in the same shelln.
As a cool side-effect, you can also use this template if you want
to interact with the contents of the learner's shell session. The
track uses `tmux` to persist the shell, and with that comes the
opportunity to read the content of the entire `tmux` …

Provides a template for preserving the shell across challenges

---

instruqt/providing-a-console/track.yml
instruqt/providing-a-console/vendor/vendor.json

TL;DR
-----
Creates a barebones lab for addding the admin console to Harbor
Details
-------
Provides a bare minimum to distinguish the new lab I'm working on so I can get the automation to see it and be able to work without setting customer URL parameters. Lab is in maintenance so should be fine.
Goal of the lab is to shift from Helm-based to KOTS-based distribution for the Harbor Helm application that's used in the Builders experience labs. We're looking for examples for this to support docs and demos, so a lab felt like a good place to start.

Barebones Admin Console track for automation

---

instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/assignment.md
instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/solve-shell

TLDR
=====
Pinning Harbor version to maintain lab version bumps
Description
====
Modified the `helm pull` command to use `helm pull --version` when pulling Harbor. This ensures that as Harbor is updated, the lab does not need to change to reflect Harbor versioning.

Pinning Harbor version

---

.github/workflows/build-shell-image.yaml
docker/shell/Dockerfile

TL;DR
-----
Shell image builds were failing and this fixes it
Details
-------
Updates the workflow to build shell images to use newer Google actions and updates the image Dockerfile to get the `kubectl` command from the `k8s.io` repos. The latter is what fixes the broken build, well the former just gets rid of warnings and assures we're using stuff that's still maintained.

Modernizes shell image build

---

instruqt/shared-env-template/01-getting-to-know-the-template/check-cluster
instruqt/shared-env-template/01-getting-to-know-the-template/check-shell
instruqt/shared-env-template/01-getting-to-know-the-template/cleanup-cluster
instruqt/shared-env-template/01-getting-to-know-the-template/cleanup-shell
instruqt/shared-env-template/01-getting-to-know-the-template/setup-cluster
instruqt/shared-env-template/01-getting-to-know-the-template/solve-cluster
instruqt/shared-env-template/01-getting-to-know-the-template/solve-shell
instruqt/shared-env-template/02-using-the-template/check-cluster
instruqt/shared-env-template/02-using-the-template/check-shell
instruqt/shared-env-template/02-using-the-template/cleanup-cluster
instruqt/shared-env-template/02-using-the-template/setup-cluster
instruqt/shared-env-template/02-using-the-template/setup-shell
instruqt/shared-env-template/02-using-the-template/solve-cluster
instruqt/shared-env-template/02-using-the-template/solve-shell
instruqt/shared-env-template/03-tips-and-tricks/check-cluster
instruqt/shared-env-template/03-tips-and-tricks/check-shell
instruqt/shared-env-template/03-tips-and-tricks/cleanup-cluster
instruqt/shared-env-template/03-tips-and-tricks/cleanup-shell
instruqt/shared-env-template/03-tips-and-tricks/setup-cluster
instruqt/shared-env-template/03-tips-and-tricks/setup-shell
instruqt/shared-env-template/03-tips-and-tricks/solve-cluster
instruqt/shared-env-template/03-tips-and-tricks/solve-shell
instruqt/shared-env-template/config.yml
instruqt/shared-env-template/track.yml
instruqt/shared-env-template/track_scripts/setup-cluster
instruqt/shared-env-template/track_scripts/setup-shell
libs/header.sh

TL;DR
-----
Improves the shared environment template based on recent lab work
Details
-------
Updates the shared environment template based on recurring lifecycle
script needs.
* Bumps Kubernetes version to 1.29.0
* Includes the header in all lifecycle scripts
* Updates maintainers and starts the track in maintenance mode
* Assures all challenges have the minimal lifecycle scripts for each
stage and host
* Uses `/usr/bin/env bash` as the shebang for all lifecycle scripts
* Sets `KUBECONFIG` or `HOME_DIR` variables  at the start of each
lifecycle script
* Sets the most used agent variables in the track setup scripts
* Adds `get_app_slug` to the header and refines it to use the
application name instead of assuming the first app is the right one
* Gets rid of old bash output of credentials …

Refines the shared environment template

---

instruqt/shared-env-template/track_scripts/setup-cluster
instruqt/shared-env-template/track_scripts/setup-shell

TL;DR
-----
Fixes an issue with were the branch header was being downloaded
Details
-------
The last updates the template got merged in with the header download in
the track setup script referring to the branch. Once the branch was
deleted it couldn't be downloaded any longer. This change fixes that.

Corrects merge issue for header download

---

instruqt/avoiding-installation-pitfalls/01-working-with-preflight-checks/assignment.md
instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/assignment.md
instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/assignment.md
instruqt/avoiding-installation-pitfalls/04-releasing-the-application/assignment.md
instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/assignment.md
instruqt/avoiding-installation-pitfalls/06-completing-the-install/assignment.md
instruqt/avoiding-installation-pitfalls/06-completing-the-install/solve-shell
instruqt/avoiding-installation-pitfalls/track.yml
instruqt/closing-information-gap/01-viewing-instance-info/assignment.md
instruqt/closing-information-gap/02-working-with-support-bundles/assignment.md
instruqt/closing-information-gap/03-additional-information/assignment.md
instruqt/closing-information-gap/04-adding-to-the-chart/assignment.md
instruqt/closing-information-gap/05-releasing-an-update/assignment.md
instruqt/closing-information-gap/06-support-bundle-diagnosis/assignment.md
instruqt/closing-information-gap/07-other-ways/assignment.md
instruqt/closing-information-gap/track.yml
instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/assignment.md
instruqt/distributing-with-replicated/02-enabling-the-sdk/assignment.md
instruqt/distributing-with-replicated/03-creating-a-release/assignment.md
instruqt/distributing-with-replicated/04-installing-the-application/assignment.md
instruqt/distributing-with-replicated/05-validating-the-install/assignment.md
instruqt/distributing-with-replicated/track.yml

TL;DR
-----
Moves the Slackernews replacements for Harbor labs to production
Details
-------
Update the track metadata to deploy the three labs original written around the Harbor registry to use Slackernews.
Covers the following labs:
* Distributing Your Application with Replicated
* Avoiding Installation Pitfalls
* Closing the Support Information Gap

Promote Slackernews Labs to production

---

.github/workflows/build-jumpbox-image.yaml
.github/workflows/build-shell-image.yaml
.github/workflows/instruqt-create-dev-track.yml
.github/workflows/instruqt-dev-track-test.yml
.github/workflows/instruqt-generate-track-slugs.yml
.github/workflows/instruqt-prod-track-test.yml
.github/workflows/instruqt-promote-dev-track.yml

Resolves nodejs 16 deprecation warnings:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20

update checkout action to v4

---

.github/workflows/build-future-node-image.yml
instruqt/delivering-as-an-appliance/config.yml
packer/future-node/jumpbox.pkr.hcl
packer/future-node/user-data.yaml
packer/future-node/variables.pkr.hcl

TL;DR
-----
Uses a unique image for machine that will be a node
Details
-------
Changes the "Delivering..." lab to use a new image for the machine that
will become an embedded cluster node. This replaces the Jumpbox image to
allow the two to vary.

Switches "Delivering..." lab to use a new image

---

instruqt/distributing-with-replicated/track.yml

TL;DR
-----
Fixes time limit on Distributing Your Application with Replicated
Details
-------
At some point along the way, I misunderstood which file I was working in
and ended up setting the timeout for the entire "Distributing Your
Application with Replicated" lab to ten minutes. This change addresses
that.

Bumps up unnaturally short time limit

---

instruqt/track-slugs.yml

TL;DR
-----
Stops test from overwriting beta lab
Details
-------
The periodic tests we run on the live labs have been overwriting the
beta lab for "Delivering Your Application as a Kubernetes Appliance" and
we can't have that. This fix moves that lab out of the testing
temporarily.

Removes EC lab from production tests

---

instruqt/delivering-as-an-appliance/01-specifying-the-cluster/assignment.md
instruqt/delivering-as-an-appliance/01-specifying-the-cluster/check-shell
instruqt/delivering-as-an-appliance/02-customize-for-your-app/assignment.md
instruqt/delivering-as-an-appliance/03-collecting-configuration/assignment.md
instruqt/delivering-as-an-appliance/03-collecting-configuration/setup-shell
instruqt/delivering-as-an-appliance/03-collecting-configuration/solve-shell
instruqt/delivering-as-an-appliance/04-using-the-configuration/assignment.md
instruqt/delivering-as-an-appliance/05-downloading-and-installing/assignment.md
instruqt/delivering-as-an-appliance/06-completing-the-install/assignment.md
instruqt/delivering-as-an-appliance/track.yml
instruqt/delivering-as-an-appliance/track_scripts/setup-node
instruqt/delivering-as-an-appliance/track_scripts/setup-shell
instruqt/track-slugs.yml
libs/header.sh

TL;DR
=====
Provides "Delivering Your Application as a Kubernetes Appliance" lab
Details
=======
Implements a lab named "Delivering Your Application as a Kubernetes
Appliance" that shows how to package and install with Slackernews with the
Replicated Embedded Cluster. 
The lab takes the user through iteratively building the Embedded Cluster
implementation of Slackernews based on the Helm chart. Once they have a
working implementation they install it as a customer then review the new
instance in the Vendor Portal.

Adds Embedded Cluster lab

---

instruqt/meet-the-platform/01-accessing-the-platform/assignment.md
instruqt/meet-the-platform/01-accessing-the-platform/check-shell
instruqt/meet-the-platform/01-accessing-the-platform/cleanup-shell
instruqt/meet-the-platform/01-accessing-the-platform/setup-shell
instruqt/meet-the-platform/01-accessing-the-platform/solve-shell
instruqt/meet-the-platform/config.yml
instruqt/meet-the-platform/track.yml
instruqt/meet-the-platform/track_scripts/setup-node
instruqt/meet-the-platform/track_scripts/setup-shell
instruqt/meet-the-platform/vendor/vendor.json

TL;DR
-----
Provides a stub for a new overview-style lab
Details
-------
Implements a stub track for "Meeting the Replicated Platform", a new lab
that vendors can use to discover the Replicated Platform. The lab will
cover some of the same steps as an overview demo to familiarize vendors
with the Platform on their own.

Starts an overview lab

---

instruqt/meet-the-platform/vendor/vendor.json

TL;DR
-----
Corrects the name of the application in vendor setup
Details
-------
Properly names the application as Slackernews

Fixes the application name

---

instruqt/delivering-as-an-appliance/01-specifying-the-cluster/solve-shell

TL;DR
-----
Makes sure the tmux sesesion exists to avoid solve script error
Details
-------
Fixes an issues where tests were failing because the solve script for
the first challenge in the "Delivering Your Application as a Kubernetes
Appliacne" lab was trying to send to tmux before the session existed.

Repairs solve for first "Delivering..." challenge
