replicatedhq/replicated-field-labs

lab1-kots/lab1-e0-hello-world/README.md

I stopped before 9 - Iterating.

Clarified some instructions. Added some TODO's

---

setup/pkg/fieldlabs/environment_create.go
terraform/main.tf

Single squid proxy per prefix

---

setup/pkg/fieldlabs/environment_create.go

- Update install script to allow for password login

- Update create environment with option for password login

---

labs/lab05-airgap/README.md

- Update lab5 README to include setup of the Replicated CLI

Update lab5 README

---

labs/lab00-hello-world/Makefile
labs/lab00-hello-world/README.md
labs/lab01-ui-analyzers/README.md
labs/lab02-adding-analyzers/README.md
labs/lab03-support-cli/README.md
labs/lab05-airgap/README.md
labs/lab06-proxy/README.md
labs_airgap.json
setup/pkg/fieldlabs/environment_create.go
terraform/main.tf

- Add intros for each lab that explain who it is for, etc
- add (...) needed in newer versions of terraform to allow multiple-prefix keys
- disable "chage" command that requires a new password on login
- add a new labs_airgap.json that just contains lab0 and lab5
- re-write airgapped to Air Gap everywhere per marketing (can change this back later after discusssion, but want to align for now)

Productize labs, other small tweaks

---

Makefile
doc/03-multi-player.md
setup/pkg/fieldlabs/environment_destroy.go
setup/pkg/fieldlabs/members.go
setup/pkg/fieldlabs/print.go
setup/pkg/fieldlabs/prompt.go

- Add members struct
- Add deletemember
- Add delete policies

Update make destroy

---

labs/lab05-airgap/README.md

Took me awhile to figure this one out, so just an update to make it clear that you must exit the vms and create the port forward on your local workstation.

Run the port forward commands on your local workstation

---

.gitignore
terraform/main.tf

Generates the following text files that can be used as starter templates 
```
==> terraform/emails/markt <==
Hi Markt - your labs have been provisioned and are ready!
Labs 00, 01, 02, 03, 07 have been provisioned.
1. Check your email and accept the invite to create an account (subject will be "Invitation to join team on replicated" from "contact@replicated.com")
2. Navigate to the first lab and start working from the readme: https://github.com/replicatedhq/kots-field-labs/tree/main/labs/lab00-hello-world
3. You will see prompts to "insert your IP address here" -- those IPs for each participant are found below. The password for each SSH login will be "password" (or try "replicated" if that doesn't work) and the UI password for logging into the browser view will be "password" (or try …
```

in the meantime - generate emails in terraform

---

instruqt/custom-fields/01-introduction/assignment.md
instruqt/helm-hello-world/01-intro/assignment.md

Adding intro folder back to Helm Hello World

Adding back Intro Folder

---

instruqt/custom-fields/03-updating-the-application/assignment.md

Added a tab for the code editor to test further

Added code tab

---

instruqt/custom-fields/01-introduction/assignment.md
instruqt/custom-fields/02-creating-custom-fields/assignment.md
instruqt/custom-fields/03-updating-the-application/assignment.md
instruqt/custom-fields/04-setting-the-custom-field/assignment.md
instruqt/custom-fields/05-admin-console-install/assignment.md
instruqt/custom-fields/05-admin-console-install/setup-kubernetes-vm
instruqt/custom-fields/06-install-application/assignment.md
instruqt/custom-fields/06-install-application/setup-kubernetes-vm
instruqt/custom-fields/07-enable-feature/assignment.md
instruqt/custom-fields/track.yml

Updates to typos and issues found while testing track

---

instruqt/custom-fields/03-updating-the-application/assignment.md
instruqt/custom-fields/vendor/manifests/nginx-service.yaml

This PR contains minor tweaks
- Simplified the nginx service to always be a `NodePort` so we can open the app
- Added a better intro to why we need to update the app
- Added more information and links on the templating functions used in the lab

Custom Fields Lab Enhancements

---

instruqt/airgap-embedded/track.yml
instruqt/track-slugs.yml

TL;DR
-----
Makes a couple of quick fix post-merge fixes to the embedded airgap lab
Details
-------
* Adds track to `track-slugs.yml` for automation
* Updates title and teaser

Quickly touches up Airgap Embedded lab

---

instruqt/airgap-embedded/01-airgap-overview/setup-jumpbox
instruqt/airgap-embedded/02-prepare-your-jumpbox/check-jumpbox
instruqt/airgap-embedded/03-airgap-deployment-assets/assignment.md
instruqt/airgap-embedded/03-airgap-deployment-assets/check-jumpbox
instruqt/airgap-embedded/05-moving-assets-into-place/check-jumpbox
instruqt/airgap-embedded/06-beginning-the-install/check-jumpbox
instruqt/airgap-embedded/07-configuring-the-application/check-jumpbox
instruqt/airgap-embedded/08-deploying-a-new-version/check-jumpbox
instruqt/airgap-embedded/08-deploying-a-new-version/cleanup-jumpbox
instruqt/airgap-embedded/08-deploying-a-new-version/setup-jumpbox
instruqt/airgap-embedded/09-troubleshooting-admin-console/check-jumpbox
instruqt/airgap-embedded/track.yml

TL;DR
-----
Addresses observations from first run through airgap lab
Details
-------
Makes a few corrections and refinesments after running through the 
arigap lab post-merge.  Some changes make the lab more consistent
with the way the vnedor portal automation has evolved since the 
intiial lab build. Others refine the lifecycle scripts based on
observing how they ran.

Edits to Airgap lab after first run through with full automation

---

instruqt/airgap-embedded/05-moving-assets-into-place/assignment.md

TL;DR
-----
Corrects filename in "Moving Assets into Place" challenge
Details
-------
Updates the "Moving Assets into Place" challenge to match the filename
convention from the current automation. Thanks to @lauren-r8d for 
reporting in #206.

Fixes file reference in "Moving Assets..."

---

.github/workflows/build-jumpbox-image.yaml
.github/workflows/build-shell-image.yaml

TL;DR
-----
Fine tunes the events that trigger image builds
Details
-------
* Makes sure that both `shell` and `jumpbox` images build on
PRs and commits to `main`
* Assures that the Jumpbox image _doesn't_ replace the active
image on pull requests (the conditional build was backwards)
* Provides a Jumpbox image build for pull requests that cleans
up after itself
* Applies a little bit of polish

Updates workflows for `shell` and `jumpbox` images

---

instruqt/short-demo/vendor/manifests/kots-app.yaml

Change demo icon

---

CONTRIBUTING.md

Proposing this, I'm not 100% sure this should be a hard and fast rule. Anyways we should have a style guide.

Create CONTRIBUTING.md (#122)

---

instruqt/short-demo/01-demo/assignment.md
instruqt/short-demo/config.yml
instruqt/short-demo/track.yml
instruqt/short-demo/track_scripts/setup-kurl

Short demo kurl

---

instruqt/custom-fields/03-updating-the-application/assignment.md

Pretty minor one, but a typo is a typo ;)

instruqt/custom-fields: fix typo

---

instruqt/short-demo/01-demo/assignment.md
instruqt/short-demo/track_scripts/setup-shell

Adding kots install output to kotsadm.log for demo purposes

---

instruqt/helm-hello-world/02-getting/assignment.md
instruqt/helm-hello-world/04-wordpress-install/assignment.md

TL;DR
-----
Corrects two times where "application" was mis-spelled
Details
-------
@kayleemchugh reported two typos in the Helm Hello Worldd lab,
both of which happened to be the word "application". I opened an
#255 to track her report and fix the errors with this change.

Fixes typos reported by Kaylee McHugh

---

instruqt/airgap-embedded/04-moving-assets-into-place/assignment.md
instruqt/airgap-embedded/08-troubleshooting-admin-console/assignment.md

Self explanatory, open to other language choices if preferred...

Fix typos in instruqt airgap lab

---

instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/assignment.md
instruqt/avoiding-installation-pitfalls/track.yml

TL;DR
-----
Fixes some issues with the second step the preflights lab
Details
-------
Corrects two minor issues on the Avoiding Installation Pitfalls lab:
* Typo on the word memory
* Bad image reference

Repairs small defects in preflights lab

---

instruqt/avoiding-installation-pitfalls/01-working-with-preflight-checks/cleanup-shell
instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/cleanup-shell
instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/cleanup-shell
instruqt/avoiding-installation-pitfalls/04-releasing-the-application/cleanup-shell
instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/cleanup-shell
instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/setup-shell
instruqt/avoiding-installation-pitfalls/06-completing-the-install/assignment.md
instruqt/avoiding-installation-pitfalls/06-completing-the-install/cleanup-shell
instruqt/avoiding-installation-pitfalls/track.yml
instruqt/distributing-with-replicated/04-installing-the-application/assignment.md

TL;DR
-----
Fixes issues identified during engineeering team Builders Plan run throughs
Details
-------
* Address feedback where the lab checks for a specific customer email but
doesn't say what it is. Builds on @diaomwiggins change.
* Fixes known issue where cleanup scripts can fail in some scenarios
* Updates language in "Distributing Your Applcation with Replicated" to account
for the customer email being set already.
* Allows the user to validating the install from the customer perspective after
the preflights lab

Fixes based on feedback from Builders Plan run throughs

---

instruqt/trying-out-cmx/01-create-a-test-cluster/assignment.md
instruqt/trying-out-cmx/01-create-a-test-cluster/check-shell
instruqt/trying-out-cmx/01-create-a-test-cluster/cleanup-shell
instruqt/trying-out-cmx/01-create-a-test-cluster/setup-shell
instruqt/trying-out-cmx/01-create-a-test-cluster/solve-shell
instruqt/trying-out-cmx/config.yml
instruqt/trying-out-cmx/track.yml
instruqt/trying-out-cmx/track_scripts/setup-shell
instruqt/trying-out-cmx/vendor/vendor.json

TL;DR
-----
Sketches out an initial skeleton for a fast CMX lab
Details
-------
Creates the track structure and first challenge for a quick lab on CMX to use at Kubecon. This PR just gets those files in place to simplify working with the lab setup as the lab gets full developed.

Quick Hit Lab for CMX (initial skeleton)

---

instruqt/protecting-your-assets/01-validate-connectivity/assignment.md
instruqt/protecting-your-assets/01-validate-connectivity/check-shell
instruqt/protecting-your-assets/config.yml
instruqt/protecting-your-assets/track.yml
instruqt/protecting-your-assets/track_scripts/setup-cluster
instruqt/protecting-your-assets/track_scripts/setup-shell
instruqt/protecting-your-assets/vendor/vendor.json

TL;DR
-----
Creates the base structure for a lab on licensing
Details
-------
Provides a barebones lab named "Protecting Your Assets with Replicated" that take users through the Replicated license and things you can do with it. This makes it easier to work with the in progress lab including, most critically, allowing `instruqt track test` to run.

Scaffolds the track Protecting Your Assets with Replicated

---

instruqt/delivering-as-an-appliance/track.yml
instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/assignment.md
instruqt/distributing-with-replicated/02-enabling-the-sdk/assignment.md
instruqt/distributing-with-replicated/03-creating-a-release/assignment.md
instruqt/distributing-with-replicated/04-installing-the-application/assignment.md
instruqt/distributing-with-replicated/05-validating-the-install/assignment.md
instruqt/distributing-with-replicated/track.yml

TL;DR
-----
Removes beta indictator on "Delivering.." lab
Details
-------
To celebrate the features covered by the "Delivering Your Application as
a Kubernetes Appliance" lab going GA, this change takes the lab out of
beta.

Takes Embedded Cluster lab out of beta

---

libs/header.sh
setup/cmd/kots-field-labs/main.go
setup/cmd/kots-field-labs/param.go

TL;DR
-----
Fixes setup and login failures for eliminated service
Details
-------
Updates all references to `id.replicated.com` to use the
`api.replicated.com` service endpoints that replaced the services from
that domain.

Repairs for deprecated service
